# dbt-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbt-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbt-core
  template:
    metadata:
      labels:
        app: dbt-core
    spec:
      containers:
        - name: dbt
          image: gcr.io/rock-extension-450317-c9/dbt-core:latest
          command: ["tail"]
          args: ["-f", "/dev/null"]
