# airflow-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
        - name: airflow
          image: gcr.io/rock-extension-450317-c9/airflow:v3
          ports:
            - containerPort: 8080
